### ISSUE TITLE
Last.FM Grid failing with blank album art

### ISSUE THREAD

**Issue by x2110311x** [camero2734/Nico-and-the-Bots#76]
src/InteractionEntrypoints/slashcommands/fm/grid.ts

It looks like it should be handling it properly, by creating a blank image (line 91)
However, if there are any albums that don't have a cover on Last.FM, it simply errors out.

If I actually went and found the offending albums on last.fm and uploaded album art to the album page, the user can then actually do their grid without error.

See chat: https://discord.com/channels/269657133673349120/470330688235765770/1208961989033066538

**Comment by camero2734** [comment]
fixed by #91
